public with sharing class CreditCardHadler {
    public CreditCardHadler() {
            public static void guardarTarjeta(List<Credit_Card__c listaTarjeta){
                for(Credit_Card__c tarjeta: listaTarjeta){
                    if(tarjeta.owner != 'Accenture TEST'){
                        if(tarjeta.Contact__c == true){
                                    
                    }
                }
            }
        }
}
